package com.nuclearboy.ui.chat.parts

data class ToolLimitNotice(
    val title: String,
    val summary: String,
    val actions: List<String>,
    val diagnosticLabel: String = "tool.protocol",
    val verificationLabel: String = "正式聊天 / stream=true / 工具定义",
    val semantics: String,
)

fun detectToolLimitNotice(content: String): ToolLimitNotice? {
    val text = content.trim()
    if (text.isBlank()) return null

    val hasLimitMarker = text.containsAnyToolMarker(TOOL_LIMIT_MARKERS)
    if (!hasLimitMarker) return null

    val needsExecution = text.containsAnyToolMarker(TOOL_ACTION_MARKERS)
    val summary = if (needsExecution) {
        "模型连接正常，但当前网关没有可用的工具调用协议或外部操作能力；本轮操作屏幕/App、访问网站、服务器、ADB/SSH、读写、运行或测试没有真实发生。"
    } else {
        "模型连接正常，但当前网关没有可用的工具调用协议；只能继续普通问答。"
    }
    val actions = if (needsExecution) {
        listOf(
            "切换到支持 tools/function_call 的网关或官方模型后重试",
            "继续问答可以保留当前模型，但不要把本轮当作已执行",
        )
    } else {
        listOf(
            "需要操作文件或运行测试时先切换工具可用模型",
            "只做说明、分析或改写时可以继续当前模型",
        )
    }

    return ToolLimitNotice(
        title = "工具受限",
        summary = summary,
        actions = actions,
        semantics = "工具受限提示：模型连接正常，但当前网关工具调用协议、前端控制或外部操作能力不可用，本轮未真实执行。",
    )
}

private val TOOL_LIMIT_MARKERS = listOf(
    "工具受限",
    "未真实执行",
    "第三方网关不支持工具调用协议",
    "没有可用工具调用协议",
    "不能调用 read_file",
    "伪造工具",
    "tool calls are not supported",
    "tools are not supported",
    "tool use is disabled",
    "tools disabled",
    "function_call unsupported",
    "function calling is not supported",
    "does not support tools",
    "no available tool",
    "no tool calls",
    "can't access local files",
    "cannot access local files",
    "can't access files",
    "cannot access files",
    "don't have access to files",
    "do not have access to files",
    "no access to the filesystem",
    "no access to file system",
    "can't run commands",
    "cannot run commands",
    "can't execute commands",
    "cannot execute commands",
    "can't execute code",
    "cannot execute code",
    "can't browse the internet",
    "cannot browse the internet",
    "can't browse the web",
    "cannot browse the web",
    "can't access the internet",
    "cannot access the internet",
    "can't access external websites",
    "cannot access external websites",
    "can't access github",
    "cannot access github",
    "no internet access",
    "no browser access",
    "can't connect to your server",
    "cannot connect to your server",
    "can't use ssh",
    "cannot use ssh",
    "can't ssh",
    "cannot ssh",
    "can't use adb",
    "cannot use adb",
    "can't interact with your device",
    "cannot interact with your device",
    "can't interact with your screen",
    "cannot interact with your screen",
    "can't interact with your app",
    "cannot interact with your app",
    "can't control your phone",
    "cannot control your phone",
    "can't control your device",
    "cannot control your device",
    "can't click buttons",
    "cannot click buttons",
    "can't tap buttons",
    "cannot tap buttons",
    "can't open apps",
    "cannot open apps",
    "can't install apps",
    "cannot install apps",
    "can't operate your phone",
    "cannot operate your phone",
    "can't see your screen",
    "cannot see your screen",
    "can only provide guidance",
    "can only provide instructions",
    "can only provide steps",
    "can only guide you",
    "can only suggest",
    "can only advise",
    "can't perform actions for you",
    "cannot perform actions for you",
    "can't do it for you",
    "cannot do it for you",
    "can't make changes for you",
    "cannot make changes for you",
    "can't actually do",
    "cannot actually do",
    "can't directly perform",
    "cannot directly perform",
    "you'll need to do it yourself",
    "you need to do it yourself",
    "can't verify",
    "cannot verify",
    "can't confirm",
    "cannot confirm",
    "can't validate",
    "cannot validate",
    "can't test it",
    "cannot test it",
    "can't run the tests",
    "cannot run the tests",
    "can't run the app",
    "cannot run the app",
    "don't have a runtime environment",
    "do not have a runtime environment",
    "don't have the environment",
    "do not have the environment",
    "no runtime environment",
    "no way to verify",
    "unable to verify",
    "unable to confirm",
    "unable to test",
    "无法访问文件",
    "不能访问文件",
    "无法运行命令",
    "不能运行命令",
    "无法执行代码",
    "不能执行代码",
    "无法联网",
    "无法访问互联网",
    "不能访问互联网",
    "无法浏览网页",
    "不能浏览网页",
    "无法访问网站",
    "不能访问网站",
    "无法访问外部网站",
    "无法连接服务器",
    "不能连接服务器",
    "无法使用 ssh",
    "不能使用 ssh",
    "无法使用 adb",
    "不能使用 adb",
    "无法操作手机",
    "不能操作手机",
    "无法控制手机",
    "不能控制手机",
    "无法操作屏幕",
    "不能操作屏幕",
    "无法点击",
    "不能点击",
    "无法点按",
    "不能点按",
    "无法打开应用",
    "不能打开应用",
    "无法安装应用",
    "不能安装应用",
    "无法看到你的屏幕",
    "不能看到你的屏幕",
    "只能提供指导",
    "只能提供建议",
    "只能给出步骤",
    "只能指导你",
    "只能建议你",
    "不能替你执行",
    "无法替你执行",
    "不能直接执行",
    "无法直接执行",
    "不能实际执行",
    "无法实际执行",
    "不能替你修改",
    "无法替你修改",
    "需要你自己执行",
    "无法验证",
    "不能验证",
    "无法确认",
    "不能确认",
    "无法测试",
    "不能测试",
    "无法运行测试",
    "不能运行测试",
    "无法运行应用",
    "不能运行应用",
    "没有运行环境",
    "没有测试环境",
    "没有办法验证",
)

private val TOOL_ACTION_MARKERS = listOf(
    "读取",
    "写入",
    "运行",
    "测试",
    "验证",
    "read_file",
    "write_file",
    "run_python",
    "工具调用",
    "read",
    "write",
    "run",
    "execute",
    "test",
    "validate",
    "function_call",
    "access",
    "command",
    "commands",
    "file",
    "files",
    "filesystem",
    "file system",
    "browse",
    "internet",
    "network",
    "web",
    "website",
    "url",
    "github",
    "server",
    "ssh",
    "adb",
    "device",
    "android",
    "screen",
    "app",
    "ui",
    "click",
    "tap",
    "button",
    "install",
    "open",
    "联网",
    "互联网",
    "网络",
    "网页",
    "网站",
    "接口",
    "github",
    "服务器",
    "手机",
    "设备",
    "屏幕",
    "应用",
    "前端",
    "界面",
    "点击",
    "点按",
    "按钮",
    "安装",
    "打开",
)

private fun String.containsAnyToolMarker(markers: List<String>): Boolean =
    markers.any { contains(it, ignoreCase = true) }
